// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "naing-react-foodstall-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://naing-react-foodstall-dev.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:f60351a8-877a-487a-94c0-589e10611b53",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mkrJXHsV3",
    "aws_user_pools_web_client_id": "648p7jra8h6ck576065ckg62hv",
    "aws_user_files_s3_bucket": "react-foodstall-storage",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
